# name: Prowler Scan

# on:
#   push:
#     branches:
#       - main

# jobs:
#   scan:
#     runs-on: ubuntu-latest
#     permissions: write-all

#     steps:
#       - name: Check out code
#         uses: actions/checkout@v4

#       - name: Configure AWS credentials with OIDC
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#           role-session-name: github-actions
#           aws-region: us-east-1 

#       - name: Installing Prowler Dependencies
#         run: |
#           sudo apt-get update
#           sudo apt install zip unzip python3-pip -y
#           sudo apt remove python3-urllib3 -y
#           sudo pip install --ignore-installed prowler matplotlib pandas numpy requests slack-sdk plotly
#           prowler --version
#           ulimit -n 4096


#       - name: Running Security Audit on AWS
#         env:
#           ACCOUNT_ID: ${{ secrets.TARGET_ACCOUNT_ID }}
#         run: |
#           for ACCOUNTID in $ACCOUNT_ID; do
#           {
#             echo $ACCOUNTID
#             prowler aws \
#               --role arn:aws:iam::$ACCOUNTID:role/ProwlerExecRole \
#               --output-directory /home/runner/work/prowler/prowler/output \
#               --output-modes html csv json-asff 
#           }
#           done
#           aws s3 cp /home/runner/work/prowler/prowler/output/ "s3://test-2025-924144197303/" --recursive

#       - name: List Prowler Output
#         run: ls -l /home/runner/work/prowler/prowler/output

#       - name: Upload Prowler Results to S3
#         run: |
#           aws s3 cp /home/runner/work/prowler/prowler/output/ s3://test-2025-924144197303/ --recursive

#       - name: Debugging Outputs
#         run: |
#           echo "Verifying S3 bucket contents:"
#           aws s3 ls s3://test-2025-924144197303/


name: Prowler Scan

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions
          aws-region: us-east-1

      - name: Installing Prowler Dependencies
        run: |
          sudo apt-get update
          sudo apt install zip unzip python3-pip -y
          sudo apt remove python3-urllib3 -y
          sudo pip install --ignore-installed prowler matplotlib pandas numpy requests slack-sdk plotly
          prowler --version
          ulimit -n 4096

      - name: Running Security Audit on AWS
        env:
          ACCOUNT_ID: ${{ secrets.TARGET_ACCOUNT_ID }}
          S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          ROLE_ARN: arn:aws:iam::${{ secrets.TARGET_ACCOUNT_ID }}:role/ProwlerExecRole
        run: |
          echo "Starting Prowler Scan"
          for ACCOUNTID in $ACCOUNT_ID; do

            echo "Assessing AWS Account: $ACCOUNTID"
            ./prowler_scan.sh \
              --role $ROLE_ARN \
              --output-directory /home/runner/work/prowler/prowler/output \
              --output-modes html csv json-asff \
              --s3-bucket $S3_BUCKET

          {
            echo $ACCOUNTID
            prowler aws --role arn:aws:iam::$ACCOUNTID:role/ProwlerExecRole --output-formats csv json-asff html
          }

          done

      - name: List Prowler Output
        run: ls -l /home/runner/work/prowler/prowler/output

      - name: Upload Prowler Results to S3
        run: |
          aws s3 cp /home/runner/work/prowler/prowler/output/ s3://${{ secrets.S3_BUCKET_NAME }}/ --recursive

      - name: Debugging Outputs
        run: |
          echo "Verifying S3 bucket contents:"
          aws s3 ls s3://${{ secrets.S3_BUCKET_NAME }}/
