name: Prowler Scan Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual execution of the workflow

permissions: write-all

jobs:
  prowler-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS credentials using GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Installing Prowler Dependencies
        run: |
          sudo apt-get update
          sudo apt install zip unzip python3-pip -y
          sudo apt remove python3-urllib3 -y
          sudo pip install --ignore-installed prowler matplotlib pandas numpy requests slack-sdk plotly
          prowler --version
          ulimit -n 4096

      # Step 3: Set execute permission for the script
      - name: Make script executable
        run: chmod +x prowler_scan.sh

      # Step 4: Run the Prowler scan
      - name: Run Prowler Scan
        run: ./prowler_scan.sh
